# Generated by Django 4.1.7 on 2023-03-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_openaikey_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaikey',
            name='name',
            field=models.CharField(default='API KEY', max_length=50),
        ),
    ]
