# Generated by Django 4.1.7 on 2023-03-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_openaikey_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaikey',
            name='max_tokens',
            field=models.SmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='openaikey',
            name='model',
            field=models.CharField(default='text-davinci-003', max_length=50),
        ),
    ]
