# Generated by Django 4.1.7 on 2023-03-23 17:11

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text',
            field=wagtail.fields.RichTextField(default=2, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
